

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PROTOCOL=https
      - WEBHOOK_URL_PLACEHOLDER
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network
    restart: unless-stopped
    depends_on:
      - ngrok

  ngrok:
    image: ngrok/ngrok:latest
    command: http n8n:5678 --host-header=rewrite --log=stdout
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    networks:
      - n8n_network
    restart: unless-stopped

volumes:
  n8n_data:

networks:
  n8n_network:
    driver: bridge
